### ISSUE TITLE
Doesn't compile; Tries to place .d files on /

### ISSUE THREAD

**Issue by kernel-pan-ic** [tesnos/kezplez-nx#11]
I'm trying to compile on Linux (Arch), but I keep getting this error:
`make -C source/mbedtls/lib all`
`make[1]: Entering directory '/somedirs/kezplez-nx/source/mbedtls/lib'`
`aes.c`
`aes.c:2119:1: fatal error: opening dependency file /aes.d: Permission denied`
 `}`
 `^`
`compilation terminated.`
`make[1]: *** [/opt/devkitpro/devkitA64/base_rules:19: aes.o] Error 1`
`make[1]: Leaving directory '/somedirs/kezplez-nx/source/mbedtls/lib'`
`make: *** [Makefile:153: build] Error 2`

If I run it with `sudo -E`, it places *.d files on /. I've tried looking through the Makefiles, but I couldn't find what exactly was going wrong. I think it's that a certain environment variable isn't set, but I wouldn't know which. I'm using normal bash.

**Comment by thestrangerdev** [comment]
I was looking into this and found the same issues identified by @garrett-davidson 

IMO, we should update the Makefile. I've opened a PR that does that.
