### ISSUE TITLE
Another 2168-0002 error

### ISSUE THREAD

**Issue by WishCow** [tesnos/kezplez-nx#12]
I get the error code mentioned in the title, when launching kezplez-nx.

FW: 5.1
Bootloader: Hekate 4.1

I have followed the steps in the readme for dumping fuses, and tsec, and have verified that the folder name (kezplex-nx) is correct.

I updated from 2.1 to 5.1 without burning fuses (with ChoidojourNX), is it possible that it's causing the crash?

**Comment by ThatNerdyPikachu** [comment]
have you compiled latest master?

**Comment by WishCow** [comment]
No, I was using 1.1 from the releases page

**Comment by Dhs92** [comment]
I am getting a 2168-0002 as well on 6.0, using 1.1 from the release page. I cannot seem to get devkita64 to compile on my arch install, so I am unable to build the latest..

**Comment by jeisoft** [comment]
Error 2168-0002
Firmware 6.0.0
ReiNX nigthly version
Kezplez 1.1

**Comment by Dhs92** [comment]
It's pinned in the Homebrew Discord, I do not have the link atm.

**Comment by Pikotaro** [comment]
which discord?

**Comment by Dhs92** [comment]
https://discord.gg/C29hYvh #switch-assistance-wip

**Comment by jeisoft** [comment]
> which discord?
I have found this: https://discordapp.com/invite/MWxPgEp
look for  #switch-assitance-wip under General discussions.... And at the top there is some pinned coments. There is a kezplez download... i have not tested yes, im at work now. But test it and give a feedback

**Comment by Guilouz** [comment]
Always 2168-0002 error for me.
Tested with Kezplez 1.1 and SX OS and also RajNX with HBmenu.
Firmware 6.0.1

**Comment by JoshuaTLOZ** [comment]
Use this version https://www.mediafire.com/file/cwsr68hnc0640z9/kezplez-nx-1.1-fix.zip/file

**Comment by prey87** [comment]
> Use this version https://www.mediafire.com/file/cwsr68hnc0640z9/kezplez-nx-1.1-fix.zip/file

also 2168-0002 error

**Comment by JoshuaTLOZ** [comment]
Mmm ... Have you followed all the steps in hecate? Including that says "for lower firmware versions only"?
(sorry if I translated something wrong)

**Comment by magarto** [comment]
Same error in 6.1 firmware with your last version and hekate 4.2

**Comment by dgr8ifier** [comment]
using 6.0.1 firmware and hekate 4.2  Gives me the same error code

**Comment by dgr8ifier** [comment]
Unless anyone else knows an easier way to install XCI without SXOS....I need to rip my keys

**Comment by GiovanH** [comment]
I had this problem too. I was able to solve it by deleting all my hekate dump information (SD:/backup), redumping the configuration info, and redumping the boot0/1 and packages.

**Comment by weegee721** [comment]
https://github.com/shchmue/kezplez-nx/releases/

**Comment by weegee721** [comment]
this worked for me

**Comment by DARKFiB3R** [comment]
> 
> 
> this worked for me

Got to step 8 and crashed for me.
