### ISSUE TITLE
Seems to crash with 2168-0002 Error no matter what i do.

### ISSUE THREAD

**Issue by GhostlyCrowd** [tesnos/kezplez-nx#2]
Your provided IPL. Booting CFW with layer FS.

**Comment by GhostlyCrowd** [comment]
Changed the folder name to "kezplez-nx" didnt think it would matter and it fixed it. can you confirm it indeed requires the folder to be named specifically, if so pointing that out in the instructions will stop false bug reports.

**Comment by tesnos** [comment]
Thank you for noticing this, I'll make sure the directory is created as part of launching the application in the next commit and update the release

**Comment by GhostlyCrowd** [comment]
Just to clarify putting the NRO and other file in /switch/kezplez/ didnt work but /switch/kezplez-nx/ did

**Comment by tesnos** [comment]
Fixed with https://github.com/tesnos/kezplez-nx/commit/ac33de9508df40d3a36c539dbbd1fe3da9bb2be7
