### ISSUE TITLE
v1.1 Crashes at 08. Error Code: 2168-0002

### ISSUE THREAD

**Issue by SparkofFate** [tesnos/kezplez-nx#20]
[log.txt](https://github.com/tesnos/kezplez-nx/files/2717352/log.txt)
OFW 6.2. Using ReiNX 2.0 as my CFW. Using NS-Atmosphere to launch it. I have the fuses.bin and tsec_keys.bin files from Hekate (the .bin file for Hekate is no longer on the SD card if that matters). I have both .nacp and .nro for the kezplez file in the kezplez-nz folder under the switch folder. I run it, it completes step 07, and a split second after starting 08, it crashes, and gives me the error code: 2168-0002.

What am I doing wrong?

Added in log file if that helps.

**Comment by kingafro000** [comment]
Having this same problem

**Comment by Purpuranitrum** [comment]
I've found a solution, just download the latest version from here >> https://github.com/shchmue/kezplez-nx/releases﻿
