### ISSUE TITLE
Counter stays at 00

### ISSUE THREAD

**Issue by onehit** [tesnos/kezplez-nx#3]
No progress appears to be made
Eventually screen goes blank
keys.txt found in sdcard, but only 2 keys?
Using ipl.bin, dumped everything (multiple times)
On 1.0.0

**Comment by tesnos** [comment]
Thanks for the issue, definitely unusual.  libnx interactions with FS on 1.0.0 have been broken in the past, so I'll try and figure out some options for users on 1.0.0 soon

**Comment by 16BitWonder** [comment]
I was having a similar issue on 2.2.0.
Left it sitting for 5 minutes and it did not progress past 00.
However switching form HBMenu 2.0 to 1.0 seemed to solve it.
Only it crashed with 2168-0002 upon completing, though that might be unrelated.

**Comment by onehit** [comment]
Just tried that @16BitWonder, no luck on 1.0.0
Awaiting further updates

**Comment by tesnos** [comment]
Please check out the latest release; it includes a slightly different set of instructions and code that should fix this issue: https://github.com/tesnos/kezplez-nx/releases/tag/v1.1

**Comment by onehit** [comment]
@tesnos Followed all instructions again and got a 2162-0002 after sitting at 17. Running again after copying the keys file it generated...

**Comment by tesnos** [comment]
Glad to hear it worked! I'm still slowly eliminating possible sources of the 2168-0002 but at least all the keys get generated first
