### ISSUE TITLE
v1.1 Crashes at 15

### ISSUE THREAD

**Issue by 16BitWonder** [tesnos/kezplez-nx#4]
Tried the new v1.1 version on 2.2.0 with both 1.0 and 2.0 HBMenu.

Re-dumped Boot 0/1 and package1 + 2 with CTCaer v3.2 (does it need to be your ipl specifically?).

All attempts resulted in a 2168-0002 error when the counter hit 15, with the keys.txt resulting
in a much less complete collection of keys than v1.0 of kezplez-nx produced.

**Comment by tesnos** [comment]
For the dumping, there's no need to use my ipl specifically, so it must be something else.  Could you send a list of the folders/files within /switch/kezplez-nx, and the same for /switch/kezplez-nx/ini1 if it exists?

**Comment by 16BitWonder** [comment]
/switch/kezplez-nx/ini1
 - boot.json
 - boot.kip1
 - decomp_spl.kip1
 - FS.json
 - FS.kip1
 - Loader.json
 - Loader.kip1
 - NCM.json
 - NCM.kip1
 - ProcessMana.json
 - ProcessMana.kip1
 - sm.json
 - sm.kip1
 - spl.json
 - spl.kip1
/switch/kezplez
 - ini1/
 - package1/
 - package2/
 - boot0.bin
 - keys.txt
 - kezplez-nx.nacp
 - kezplez-nx.nro
 - package1.bin

**Comment by ijuintekka** [comment]
Also on 2.2.0 with the exact same issue. Crashes at 15 with last output titlekek_04 on line 47.

**Comment by Koichan66** [comment]
I obtained the key using kezplez-nx v1.1. Switch version is FW 1.0.0.
The application will stack at 17 and an error will occur.
Only 56 keys can be acquired.
I am dumping "Backup eMMC BOOT0/1" and "Dump package1/2".
![dkdpgoluwaao8gu](https://user-images.githubusercontent.com/39878956/44046329-1b7d13f0-9f66-11e8-95c3-e4a3405f2b37.jpg)
![dkdpgwhuwaid8iy](https://user-images.githubusercontent.com/39878956/44046341-21f44df2-9f66-11e8-8b9d-b1ea8c638859.jpg)
![dkdphtuuuaanwgt](https://user-images.githubusercontent.com/39878956/44046350-26666d84-9f66-11e8-8806-315bff942848.jpg)

**Comment by Koichan66** [comment]
Hello,
I obtained the key using kezplez-nx v1.1. Switch version is FW 1.0.0.
The application will stack at 17 and an error will occur.
Only 56 keys can be acquired.
I am dumping "Backup eMMC BOOT0/1" and "Dump package1/2".

![dkdpgoluwaao8gu](https://user-images.githubusercontent.com/39878956/44046527-af1d350e-9f66-11e8-8a2d-8685de286c5d.jpg)

![dkdpgwhuwaid8iy](https://user-images.githubusercontent.com/39878956/44046531-b2904b2c-9f66-11e8-8d63-5502a574073c.jpg)

![dkdphtuuuaanwgt](https://user-images.githubusercontent.com/39878956/44046533-b4bf4894-9f66-11e8-8b32-b732247de479.jpg)

**Comment by Kouchan66** [comment]
Hello,
I obtained the key using kezplez-nx v1.1. Switch version is FW 1.0.0.
The application will stack at 17 and an error will occur.
Only 56 keys can be acquired.
I am dumping "Backup eMMC BOOT0/1" and "Dump package1/2".

![dkdpgoluwaao8gu](https://user-images.githubusercontent.com/39878956/44046728-50795608-9f67-11e8-9dcf-4f48be0f28e8.jpg)

![dkdpgwhuwaid8iy](https://user-images.githubusercontent.com/39878956/44046731-5307177a-9f67-11e8-943a-f57122238572.jpg)

![dkdphtuuuaanwgt](https://user-images.githubusercontent.com/39878956/44046733-5528c04e-9f67-11e8-9616-67ba92596eee.jpg)

**Comment by shchmue** [comment]
firmwares 2.1.0-2.3.0 (same pkg1 for all three) have an issue where the SPL.kip1 rodata section length is inconsistent between the kip1 header and the section footer. should be working now.

https://github.com/shchmue/kezplez-nx/commit/6ed0024cd87bef23bd1c0644a8f2172a0d833cbf
https://github.com/shchmue/kezplez-nx/releases/tag/v1.1.3

**Comment by 16BitWonder** [comment]
Just tried @shchmue's fix on 2.2.0 and can confirm success.
Thank you for fixing this issue.

**Comment by jeannustre** [comment]
Had the same issue on FW 4.1.0, @shchmue's version also fixed it for me. Thanks !
