### ISSUE TITLE
No option to dump the tsec keys in Hekate

### ISSUE THREAD

**Issue by oGamefreak** [tesnos/kezplez-nx#5]
Not sure how you are supposed to dump this to an sd card when only the fuses seem to have that option. I'm on 4.1.0 and have tried Hekate 3.2 and hekate-ipl-50x port for 4.x and both only let you see the keys but not actually dump them.

**Comment by lanarchyste** [comment]
Currently, the official version of Hekate does not have the option to dump the TSC key.

You have to use the payload ipl.bin, which is a Hekate mod, provided in the kezplez-nx release. This mod allows to dump the key.

**Comment by tesnos** [comment]
^, use the ipl.bin provided with releases until hekate v3.3 comes out
