### ISSUE TITLE
Other keys

### ISSUE THREAD

**Issue by mariogamer2** [tesnos/kezplez-nx#8]
Some keys are currently missing, like eticket_rsa_kek, some ssl keys and others.
Is it possible to dump them?

**Comment by CaitSith2** [comment]
Ditto.  I would love to not have to reference "search google for eticket_rsa_kek" in my tools readme, given that it should exist somewhere within the switch firmware somehow.  (My tool will load that key from keys.txt if it is present there.)

**Comment by mariogamer2** [comment]
I think those are missing:
eticket_rsa_* keys
rsa_* keys
ssl_* keys


All of those might not be super useful, so you can see which one to include.

(if someone can add more to the list, it wiuld be appreciated)

**Comment by shchmue** [comment]
[This post](https://gbatemp.net/threads/release-python-script-to-generate-the-rsa_kek.502699/#post-7950866) lists the locations of `eticket_rsa_kek_source`, `eticket_rsa_kekek_source`, `rsa_oaep_kek_generation_source` and the script in that thread generates `eticket_rsa_kek` using them. I was going to try to add them to `kezplez-nx` myself but I can't get it to run at all anymore, nothing but `2168-0002` on run after creating empty `keys.txt`.
