### ISSUE TITLE
actual master version doesn't compiling

### ISSUE THREAD

**Issue by shadow2560** [tesnos/kezplez-nx#9]
I have set all the libraries but doesn't want to compile. I use a devkitpro Windows environement.

Errors messages:

> C:\a\kezplez-nx>make
> make -C source/mbedtls/lib all
> make[1]: Entering directory '/c/a/kezplez-nx/source/mbedtls/lib'
> make[1]: Leaving directory '/c/a/kezplez-nx/source/mbedtls/lib'
> upload.c
> aarch64-none-elf-gcc -MMD -MP -MF /upload.d -g -Wall -O2 -ffunction-sections -march=armv8-a -mtune=cortex-a57 -mtp=soft -fPIE  `freetype-config --cflags` -I/c/a
> /kezplez-nx/include -I/opt/devkitpro/portlibs/switch/include -I/opt/devkitpro/libnx/include -I/c/a/kezplez-nx/source/mbedtls/include -I/c/a/kezplez-nx/build -D_
> _SWITCH__ -c -c /c/a/kezplez-nx/source/upload.c -o upload.o
> C:/a/kezplez-nx/source/upload.c: In function 'upload_keyfile':
> C:/a/kezplez-nx/source/upload.c:50:3: error: 'keyfile' undeclared (first use in this function); did you mean 'tmpfile'?
>    keyfile = fopen(keyfile_path, FMODE_READ);
>    ^~~~~~~
>    tmpfile
> C:/a/kezplez-nx/source/upload.c:50:3: note: each undeclared identifier is reported only once for each function it appears in
> C:/a/kezplez-nx/source/upload.c: In function 'upload_exit':
> C:/a/kezplez-nx/source/upload.c:75:8: error: 'chunk' undeclared (first use in this function)
>    free(chunk.memory);
>         ^~~~~
> make[1]: *** [/opt/devkitpro/devkitA64/base_rules:19: upload.o] Error 1
> make: *** [Makefile:155: build] Error 2

**Comment by shchmue** [comment]
Indeed the `upload` functions are commented out in `main` but upload.c doesn't currently declare `keyfile` in `upload_keyfile()` or `chunk` in `upload_exit()`. Declaring them or deleting `upload` altogether are workarounds.
